### ISSUE TITLE
create vm error with csr 1000v image.

### ISSUE THREAD

**Issue by xiaopeng163** [ios-xr/iosxrv-x64-vbox#28]
```bash
python iosxe_iso2vbox.py ~/Downloads/csr1000v-universalk9.03.16.04b.S.155-3.S4b-ext.iso
==> Check whether "socat" is installed
==> Input ISO is /Users/penxiao/Downloads/csr1000v-universalk9.03.16.04b.S.155-3.S4b-ext.iso
==> Creating VirtualBox VM
==> Starting VM...
==> Successfully started to boot VM disk image
==> Waiting for IOS XE to boot (may take 3 minutes or so)
Traceback (most recent call last):
  File "iosxe_iso2vbox.py", line 648, in <module>
    main(sys.argv[1:])
  File "iosxe_iso2vbox.py", line 586, in main
    configure_xe(args.verbose < logging.WARN)
  File "iosxe_iso2vbox.py", line 354, in configure_xe
    raise pexpect.TIMEOUT('Timeout (%s) exceeded in read().' % str(child.timeout))
pexpect.exceptions.TIMEOUT: Timeout (600) exceeded in read().
```

**Comment by remingtonc** [comment]
This looks like it is due to the XE image not booting fast enough.

You can try using a more powerful machine, or change this line to have a higher timeout value (like 1200 for 20 minutes, etc.).
https://github.com/ios-xr/iosxrv-x64-vbox/blob/master/iosxe_iso2vbox.py#L259
