### ISSUE TITLE
iosxe_iso2vbox.py fails for csr1000v-universalk9.16.08.01a.iso 

### ISSUE THREAD

**Issue by termlen0** [ios-xr/iosxrv-x64-vbox#38]
Box creation fails at the socat stage. Trying to manually connect to the serial port also fails (I tried non-tcp options as well on a standalone). 

```
❯❯❯ python iosxe_iso2vbox.py ~/Downloads/csr1000v-universalk9.16.08.01a.iso                         ✘ 1 
==> Check whether "socat" is installed
==> Input ISO is /home/achenamp/Downloads/csr1000v-universalk9.16.08.01a.iso
==> Creating VirtualBox VM
==> Starting VM...
==> Successfully started to boot VM disk image
==> Waiting for IOS XE to boot (may take 3 minutes or so)






Traceback (most recent call last):
  File "iosxe_iso2vbox.py", line 648, in <module>
    main(sys.argv[1:])
  File "iosxe_iso2vbox.py", line 586, in main
    configure_xe(args.verbose < logging.WARN)
  File "iosxe_iso2vbox.py", line 354, in configure_xe
    raise pexpect.TIMEOUT('Timeout (%s) exceeded in read().' % str(child.timeout))
pexpect.exceptions.TIMEOUT: Timeout (600) exceeded in read().
```

**Comment by hpreston** [comment]
@termlen0 This is because the last few images posted for the CSR don't have the Serial port available by default in the MBR.  Working off the great work by @rschmied I built a quick process that fixes the ISO so you can script it.  I've got it all documented in my "box building" instructions here.  

https://github.com/hpreston/vagrant_net_prog/blob/master/box_building/README.md#cisco-csr-1000v
